assistant:
  name: "Student Research Assistant"
  model:
    provider: "google"
    model: "gemini-1.5-flash"
    system_prompt_template: |
      You are a Student Research Assistant powered by LangGraph. Your responses should be:
      
      **FOR STUDENTS:**
      - Help with research papers, assignments, and academic projects
      - Provide clear, educational explanations suitable for learning
      - Break down complex topics into digestible parts
      - Offer study tips and research methodologies
      
      **VOICE-OPTIMIZED FOR STUDENTS:**
      - Use conversational, friendly language
      - Keep responses concise (2-3 sentences) for voice calls
      - Ask clarifying questions about assignment requirements
      - Provide step-by-step guidance when needed
      
      **RESEARCH CAPABILITIES:**
      - Use quick_research for immediate answers during voice calls
      - Use comprehensive_research for detailed academic research
      - Use content_generation for assignments and projects
      
      Always be encouraging and supportive. Focus on helping students learn and understand concepts.

  voice:
    provider: "playht"
    voiceId: "jennifer-playht"
  
  firstMessage: "Hi! I'm your Student Research Assistant. I can help you with research, assignments, and academic projects. What are you working on today?"

tools:
  - name: "quick_research"
    description: "Get immediate research answers optimized for voice calls (2-5 seconds)"
    parameters:
      type: "object"
      properties:
        query:
          type: "string"
          description: "Your research question or academic topic"
        max_sources:
          type: "integer"
          description: "Maximum number of sources (1-3 for quick response)"
          minimum: 1
          maximum: 3
          default: 2
        academic_focus:
          type: "boolean"
          description: "Focus on academic and educational sources"
          default: true
      required: ["query"]
    action:
      type: "api_call"
      method: "POST"
      url: "https://ba54-2603-8000-ba00-34c9-2046-d24b-6925-bbb0.ngrok-free.app/webhook/tool-call"
      json_body:
        query: "{query}"
        max_sources: "{max_sources}"
        academic_focus: "{academic_focus}"
      response_template: "Let me quickly research that for you..."

  - name: "comprehensive_research"
    description: "Detailed academic research with multiple sources and citations"
    parameters:
      type: "object"
      properties:
        topic:
          type: "string"
          description: "The academic topic for detailed research"
        research_depth:
          type: "string"
          description: "How comprehensive the research should be"
          enum: ["basic", "detailed", "comprehensive"]
          default: "detailed"
        include_citations:
          type: "boolean"
          description: "Include academic citations and references"
          default: true
        academic_level:
          type: "string"
          description: "Academic level for appropriate complexity"
          enum: ["high_school", "undergraduate", "graduate"]
          default: "undergraduate"
      required: ["topic"]
    action:
      type: "api_call"
      method: "POST"
      url: "https://ba54-2603-8000-ba00-34c9-2046-d24b-6925-bbb0.ngrok-free.app/webhook/tool-call"
      json_body:
        topic: "{topic}"
        research_depth: "{research_depth}"
        include_citations: "{include_citations}"
        academic_level: "{academic_level}"
      response_template: "I'll conduct comprehensive research on {topic} for you..."

  - name: "generate_content"
    description: "Generate academic content, essays, summaries, and study materials"
    parameters:
      type: "object"
      properties:
        content_type:
          type: "string"
          description: "Type of content to generate"
          enum: ["essay_outline", "summary", "study_notes", "presentation_outline", "research_proposal"]
        topic:
          type: "string"
          description: "Topic or subject for content generation"
        length:
          type: "string"
          description: "Desired length of content"
          enum: ["short", "medium", "long"]
          default: "medium"
        academic_style:
          type: "boolean"
          description: "Use formal academic writing style"
          default: true
        include_sources:
          type: "boolean"
          description: "Include reference sources"
          default: true
      required: ["content_type", "topic"]
    action:
      type: "api_call"
      method: "POST"
      url: "https://ba54-2603-8000-ba00-34c9-2046-d24b-6925-bbb0.ngrok-free.app/webhook/tool-call"
      json_body:
        content_type: "{content_type}"
        topic: "{topic}"
        length: "{length}"
        academic_style: "{academic_style}"
        include_sources: "{include_sources}"
      response_template: "I'll generate {content_type} on {topic} for you..." 