assistant:
  name: "Tesseract Command Assistant"
  model:
    provider: "openai"
    model: "gpt-4o-mini"
    system_prompt_template: >
      You are a specialized AI assistant for the Tesseract system. Your goal is to accurately trigger the correct tool based on the user's request.

      CRITICAL RULES:
      1. If the user's request clearly matches a specific workflow tool like 'triggerFinancialAnalysisWorkflow', ask for any missing parameters and then call that tool.
      2. For ALL OTHER requests, including simple questions, greetings, or ambiguous commands, you MUST use the 'processGeneralRequest' tool. Do not try to answer yourself.
      3. The user's ID is {user_id}.

      Example 1: User says "I need a financial analysis of Tesla". You should ask clarifying questions for 'analysis_type', then call 'triggerFinancialAnalysisWorkflow'.
      Example 2: User says "What's the weather?" or "Hello there". You MUST call 'processGeneralRequest'.
  voice: 
    provider: "playht"
    voiceId: "jennifer-playht"
  firstMessage: "Tesseract system online. How can I assist you?"

tools:
  # TOOL 1: For specific, known workflows
  - name: "triggerFinancialAnalysisWorkflow"
    description: "Use this specific tool to run a multi-step financial analysis on a company. Requires the company name and the type of analysis."
    parameters:
      type: "object"
      properties:
        user_id:
          type: "string"
          description: "The user's unique ID."
        company_name:
          type: "string"
          description: "The name of the company to analyze, e.g., 'Tesla Inc'."
        analysis_type:
          type: "string"
          description: "The type of analysis to run, e.g., 'credit_risk', 'standard_review'."
      required: ["user_id", "company_name", "analysis_type"]
    action:
      type: "api_call"
      method: "POST"
      url: "http://localhost:8081/run_workflow/financial_analysis/{user_id}"
      json_body:
        input_params:
          company_name: "{company_name}"
          analysis_type: "{analysis_type}"
      response_template: "Workflow initiated. The Job ID is {job_id}."

  # TOOL 2: The general-purpose fallback
  - name: "processGeneralRequest"
    description: "A general-purpose tool for all other requests, simple questions, or ambiguous commands that do not fit a specific workflow."
    parameters:
      type: "object"
      properties:
        user_id:
          type: "string"
          description: "The user's unique ID."
        user_input:
          type: "string"
          description: "The user's full, verbatim request."
      required: ["user_id", "user_input"]
    action:
      type: "api_call"
      method: "POST"
      url: "http://localhost:8081/receive_user_input/{user_id}"
      json_body:
        user_input: "{user_input}"
      response_path: "response" 