"""add updated_at and error_message to jobs table

Revision ID: c7b18541eea8
Revises: 
Create Date: 2025-06-13 12:08:51.201356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b18541eea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'updated_at')
    # ### end Alembic commands ###
